### ISSUE TITLE
Missing important step at install

### ISSUE THREAD

**Issue by lucasdiedrich** [adrien2p/teanjs#2]
It should be told that before running npm install we should install OS dependencies before, like: dnf install libpq-devel on fedora. 

Without that the output below is shown:
```bash
> libpq@1.8.9 install /home/lucas.diedrich/Documentos/projects/dev/capisenha/node_modules/libpq
> node-gyp rebuild

find: ‘/usr/pg*’: No such file or directory
find: ‘/opt/containerd’: Permission denied
gyp: Call to 'which pg_config || find /usr/bin /usr/local/bin /usr/pg* /opt -executable -name pg_config -print -quit' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/lucas.diedrich/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.17-200.fc31.x86_64
gyp ERR! command "/home/lucas.diedrich/.nvm/versions/node/v10.18.1/bin/node" "/home/lucas.diedrich/.nvm/versions/node/v10.18.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/lucas.diedrich/Documentos/projects/dev/capisenha/node_modules/libpq
gyp ERR! node -v v10.18.1
gyp ERR! node-gyp -v v5.0.7
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! libpq@1.8.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the libpq@1.8.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/lucas.diedrich/.npm/_logs/2020-02-13T16_44_18_946Z-debug.log

```

**Comment by adrien2p** [comment]
Thank you very much fir this information. I wasn’t aware about those dependencies issues on fedora distribution. This issue could be helpful for people’s using the same distribution.
